# Auditoria e Tratamento de Dados - Nara Hotéis

## Objetivo

O objetivo deste projeto é realizar uma auditoria completa nos conjuntos de dados operacionais da rede Nara Hotéis, identificando inconsistências, avaliando a qualidade dos registros e aplicando os tratamentos necessários para garantir a confiabilidade das informações.

A auditoria será conduzida individualmente em cada DataFrame, seguindo as etapas de:

- Diagnóstico da estrutura dos dados;
- Identificação de inconsistências;
- Correção e padronização dos registros;
- Validação das alterações realizadas.

In [1]:
import pandas as pd
import numpy as np

In [2]:
## from google.colab import drive
## drive.mount('/content/drive')

In [3]:
## df_canais_venda = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/canais_venda.csv', sep=';', decimal=',')
## df_clientes = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/clientes.csv', sep=';', decimal=',')
## df_funcionarios = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/funcionarios.csv', sep=';', decimal=',')
## df_reservas = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/reservas.csv', sep=';', decimal=',')
## df_tipos_quarto = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/tipos_quarto.csv', sep=';', decimal=',')
## df_unidades = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Nara Hoteis/unidades.csv', sep=';', decimal=',')

In [4]:
df_canais_venda = pd.read_csv('canais_venda.csv', sep=';', decimal=',')
df_clientes = pd.read_csv('clientes.csv', sep=';', decimal=',')
df_funcionarios = pd.read_csv('funcionarios.csv', sep=';', decimal=',')
df_reservas = pd.read_csv('reservas.csv', sep=';', decimal=',')
df_tipos_quarto = pd.read_csv('tipos_quarto.csv', sep=';', decimal=',')
df_unidades = pd.read_csv('unidades.csv', sep=';', decimal=',')

# Auditoria do DataFrame Canais de Venda

Este conjunto contém informações sobre os canais utilizados para comercialização das reservas. Nesta etapa será realizada uma análise da estrutura dos dados, identificação de inconsistências e aplicação dos tratamentos necessários para garantir a padronização dos registros.

In [5]:
## Analisando estrutura, tipos de dados e padrões de preenchimento

df_canais_venda.info()
display(df_canais_venda.dtypes)
display(df_canais_venda.describe(include='str'))
df_canais_venda

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_canal      4 non-null      int64
 1   nome_canal    4 non-null      str
 2   comissao_pct  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

id_canal        int64
nome_canal        str
comissao_pct      str
dtype: object

          nome_canal comissao_pct
count              4            4
unique             4            4
top     Site Próprio           8%
freq               1            1

   id_canal    nome_canal comissao_pct
0         1  Site Próprio           8%
1         2           ota          18%
2         3      Telefone           5%
3         4       agencia          12%

 Problemas identificados no DataFrame Canais de Vendas

| Coluna | Problema | Quantidade | Severidade |
|---------|-----------|------------|------------|
| nome_canal | Padrão de texto | 2 | 🟢 Baixa |
| comissao_pct | Valores armazenados como texto; necessário remover '%'; e converter para float. | 4 | 🟡 Média |

In [6]:
## Tratando inconsistências identificadas durante a auditoria

## Convertendo a comissão para formato numérico adequado para análise
df_canais_venda['comissao_pct'] = (
    df_canais_venda['comissao_pct']
    .astype(str).str.replace('%', '', regex=False)
    .astype(float))
df_canais_venda['comissao_pct'] = (pd.to_numeric(df_canais_venda['comissao_pct'], errors='coerce'))

## Padronizando nomenclaturas dos canais de venda
df_canais_venda['nome_canal'] = (
    df_canais_venda['nome_canal']
    .str.title()
    .replace('Ota', 'OTA'))


## Validando as alterações aplicadas
df_canais_venda.info()
df_canais_venda

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_canal      4 non-null      int64
 1   nome_canal    4 non-null      str
 2   comissao_pct  4 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 228.0 bytes

   id_canal    nome_canal  comissao_pct
0         1  Site Próprio           8.0
1         2           OTA          18.0
2         3      Telefone           5.0
3         4       Agencia          12.0

# Auditoria do DataFrame Tipos de Quarto

Esta base reúne as categorias de acomodação disponibilizadas pela rede. O objetivo da auditoria é verificar a consistência dos valores monetários, identificar duplicidades e padronizar as descrições dos quartos.

In [7]:
## Avaliando estrutura, tipos de dados e qualidade dos registros

df_tipos_quarto.info()
display(df_tipos_quarto.dtypes)
display(df_tipos_quarto.describe(include='str'))
df_tipos_quarto

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_tipo_quarto     6 non-null      int64
 1   descricao          6 non-null      str
 2   capacidade_max     6 non-null      int64
 3   valor_diaria_base  6 non-null      str
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

id_tipo_quarto       int64
descricao              str
capacidade_max       int64
valor_diaria_base      str
dtype: object

       descricao valor_diaria_base
count          6                 6
unique         5                 5
top       Deluxe         R$ 580,00
freq           2                 2

   id_tipo_quarto     descricao  capacidade_max valor_diaria_base
0               1      STANDARD               2         R$ 280,00
1               2     superior                2         R$ 420,00
2               3        Deluxe               3         R$ 580,00
3               4         Suite               4         R$ 950,00
4               5  Suíte Master               4       R$ 1.500,00
5               3        Deluxe               3         R$ 580,00

Diagnóstico de Qualidade dos Dados

| Coluna | Problema Identificado | Quantidade de Ocorrências | Severidade |
|---------|----------------------|--------------------------|------------|
| descricao | Falta de padronização na capitalização dos valores textuais | 6 | 🟢 Baixa |
| valor_diaria_base | Armazenamento incorreto de valores monetários como texto, exigindo remoção do prefixo 'R$' e conversão para float. | 4 | 🟡 Média |
| *Registro* | Presença de registros duplicados | 2 | 🔴 Alta |

In [8]:
## Aplicando correções identificadas na etapa de diagnóstico

## Convertendo valores monetários para formato numérico
df_tipos_quarto['valor_diaria_base'] = (
    df_tipos_quarto['valor_diaria_base']
    .astype(str)
    .str.replace('R$', '', regex=False)
    .str.strip()
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False).astype(float)
)
df_tipos_quarto['valor_diaria_base'] = pd.to_numeric(
    df_tipos_quarto['valor_diaria_base'],errors='coerce')

## Removendo duplicatas
df_tipos_quarto = df_tipos_quarto.drop_duplicates()

## Padronizando descrições dos tipos de quarto
df_tipos_quarto['descricao'] = df_tipos_quarto['descricao'].str.title().str.strip()
df_tipos_quarto

   id_tipo_quarto     descricao  capacidade_max  valor_diaria_base
0               1      Standard               2              280.0
1               2      Superior               2              420.0
2               3        Deluxe               3              580.0
3               4         Suite               4              950.0
4               5  Suíte Master               4             1500.0

# Auditoria do DataFrame Unidades

Nesta etapa serão auditadas as informações cadastrais das unidades hoteleiras, com foco na padronização dos dados geográficos, categorias dos hotéis e capacidade operacional.

In [9]:
## Avaliando estrutura, completude e consistência dos registros

df_unidades.info()
display(df_unidades.describe(include='str'))
df_unidades

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_unidade         12 non-null     int64
 1   nome_unidade       12 non-null     str
 2   cidade             12 non-null     str
 3   regiao             12 non-null     str
 4   categoria_hotel    12 non-null     str
 5   num_quartos_total  10 non-null     str
dtypes: int64(1), str(5)
memory usage: 708.0 bytes

,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
count,12,12,12,12,10
unique,12,8,8,7,7
top,NaraHoteis Ipanema,Rio de Janeiro,Costa Verde,4 estrelas,60.0
freq,1,4,3,4,2

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada fluminense,3 estrelas,55.0
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 estrelas,NaN
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

In [10]:
## Analisando variações de preenchimento nas colunas categóricas

display(df_unidades['regiao'].value_counts())
display(df_unidades['categoria_hotel'].value_counts())

regiao
Costa Verde           3
Capital               2
Serra                 2
capital               1
CAP                   1
Baixada Fluminense    1
Baixada fluminense    1
Serra                 1
Name: count, dtype: int64

categoria_hotel
4 estrelas        4
5 estrelas        3
3*                1
Três Estrelas     1
3 estrelas        1
4 Estrelas        1
cinco estrelas    1
Name: count, dtype: int64

Diagnóstico de Qualidade dos Dados

| Coluna            | Problema Identificado                                                                 | Quantidade de Ocorrências | Severidade |
|-------------------|----------------------------------------------------------------------------------------|---------------------------|------------|
| regiao            | Inconsistência na padronização de valores textuais (variações de capitalização e abreviações) | 9                         | 🟡 Média |
| categoria_hotel   | Inconsistência na padronização de categorias textuais (variações de escrita) | 10                        | 🟡 Média |
| dtypes            | Tipagem de dados inadequada, com necessidade de conversão para tipos apropriados | 4                         | 🟡 Média |
| num_quartos_total | Presença de valores nulos. Após validação junto aos hotéis, os valores corretos foram informados e corrigidos. | 2                         | 🟡 Média |

In [11]:
df_unidades.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_unidade         12 non-null     int64
 1   nome_unidade       12 non-null     str
 2   cidade             12 non-null     str
 3   regiao             12 non-null     str
 4   categoria_hotel    12 non-null     str
 5   num_quartos_total  10 non-null     str
dtypes: int64(1), str(5)
memory usage: 708.0 bytes

In [12]:
## Aplicando correções identificadas no DataFrame Unidades

## Padronizando nomenclaturas das regiões
df_unidades['regiao'] = (
    df_unidades['regiao']
    .str.strip()
    .str.title()
    .replace({'Cap': 'Capital'})
)

## Padronizando categorias dos hotéis
df_unidades['categoria_hotel'] = (
    df_unidades['categoria_hotel']
    .str.strip()
    .str.title()
)

mapa = {
    '3*': '3 Estrelas',
    'Três Estrelas': '3 Estrelas',
    'Cinco Estrelas': '5 Estrelas'
}
df_unidades['categoria_hotel'] = df_unidades['categoria_hotel'].replace(mapa)

df_unidades['num_quartos_total'] = (
    df_unidades['num_quartos_total']
    .astype(float)
    .astype('Int64'))

## Corrigindo os valores nulos com os informados pela empresa
correcoes = {
    7: 70,
    10: 65}

for id_unidade, num_quartos_total in correcoes.items():
    df_unidades.loc[
        df_unidades['id_unidade'] == id_unidade,
        'num_quartos_total'
    ] = num_quartos_total

df_unidades = df_unidades.astype({
    'cidade': 'string',
    'regiao': 'string',
    'categoria_hotel': 'string'})


display(df_unidades)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 Estrelas,80
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,Capital,4 Estrelas,120
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3 Estrelas,60
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,Capital,4 Estrelas,45
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,3 Estrelas,50
5,6,NaraHoteis Nova Iguaçu Park,Nova Iguaçu,Baixada Fluminense,3 Estrelas,55
6,7,NaraHoteis Petrópolis,Petrópolis,Serra,5 Estrelas,70
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 Estrelas,55
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 Estrelas,65
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,5 Estrelas,90
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 Estrelas,50

# Auditoria do DataFrame Clientes

O objetivo desta etapa é validar a consistência dos cadastros de clientes, verificando duplicidades, padronização de informações e integridade dos identificadores.

In [13]:
## Avaliando estrutura e qualidade dos registros cadastrais

df_clientes.info()
df_clientes

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     301 non-null    int64
 1   nome           301 non-null    str
 2   cidade_origem  301 non-null    str
 3   estado_origem  301 non-null    str
 4   faixa_etaria   272 non-null    str
 5   tipo_cliente   301 non-null    str
dtypes: int64(1), str(5)
memory usage: 14.2 KB

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física
...,...,...,...,...,...,...
296,297,Roberta Leite,Curitiba,DF,56-65,pessoa fisica
297,298,Eduardo Lopes,São Paulo,ES,36-45,PJ
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [14]:
## Analisando variações de preenchimento nas colunas Estado e Tipo de Cliente

display(df_clientes['estado_origem'].value_counts())
display(df_clientes['tipo_cliente'].value_counts())

estado_origem
CE                27
PE                26
ES                24
PA                24
SC                23
SP                22
DF                22
RS                20
BA                20
MG                20
PR                19
AM                18
GO                16
RJ                16
Rio de Janeiro     2
rj                 1
r.j.               1
Name: count, dtype: int64

tipo_cliente
Corporativo      127
Pessoa Física    103
corporativo       17
PJ                15
pessoa fisica     15
PF                14
pf                10
Name: count, dtype: int64

In [15]:
## Verificando possíveis duplicidades nos identificadores dos clientes

relatorio_duplicados = pd.DataFrame({
    'coluna': df_clientes.columns,
    'duplicados': [df_clientes[col].duplicated().sum()
                   for col in df_clientes.columns]
})

display(relatorio_duplicados)

df_clientes[df_clientes.duplicated(subset=['id_cliente'], keep=False)]

          coluna  duplicados
0     id_cliente           1
1           nome         228
2  cidade_origem         292
3  estado_origem         284
4   faixa_etaria         294
5   tipo_cliente         294

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
46,47,Wesley Araujo,Recife,ES,65+,Pessoa Física
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

Diagnóstico de Qualidade dos Dados Clientes

| Coluna         | Problema Identificado                                                                 | Quantidade de Ocorrências | Severidade |
|----------------|----------------------------------------------------------------------------------------|---------------------------|------------|
| nome           | Presença de espaços em branco no início e/ou fim dos valores textuais                 | Todas                    | 🟢 Baixa   |
| faixa_etaria   | Presença de valores nulos em campo opcional (impacto medido em análise de completude)  | 9,63%                     | 🟢 Baixa   |
| estado_origem  | Inconsistência na padronização de valores textuais                                    | 4                         | 🟡 Média   |
| tipo_cliente   | Inconsistência na padronização de valores textuais                                    | 174                       | 🟡 Média   |
| dtypes         | Tipagem incorreta ou inconsistente em todas as colunas, exigindo ajuste de tipos de dados | Todas                    | 🟡 Média   |
| id_cliente     | Identificação de registros duplicados (violação de unicidade da chave primária)       | 2                         | 🔴 Alta    |

In [16]:
## Aplicando correções e padronizações cadastrais

## Padronizando o texto do nome do cliente
df_clientes['nome'] = df_clientes['nome'].str.strip()

mapa = {
    'Rio de Janeiro' : 'RJ', 'r.j.' : 'RJ', 'rj' : 'RJ',
    'pessoa fisica' : 'PF', 'corporativo' : 'Corporativo', 'Pessoa Física' : 'PF', 'pf' : 'PF', 'PJ':'Corporativo',
}
df_clientes['estado_origem'] = df_clientes['estado_origem'].replace(mapa)
df_clientes['tipo_cliente'] = df_clientes['tipo_cliente'].replace(mapa)


## Avaliando impacto dos valores ausentes na faixa etária
print(f"Percentual de nulos em faixa_etaria: {df_clientes['faixa_etaria'].isna().mean() * 100:.2f}%")

display(df_clientes)

Percentual de nulos em faixa_etaria: 9.63%

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,Corporativo
1,2,Larissa Sousa,Curitiba,SC,18-25,PF
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,Corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,PF
...,...,...,...,...,...,...
296,297,Roberta Leite,Curitiba,DF,56-65,PF
297,298,Eduardo Lopes,São Paulo,ES,36-45,Corporativo
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,PF
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [17]:
## Corrigindo conflito de unicidade na chave primária dos clientes

## Corrigindo o Id Duplicado.
df_clientes.at[300, 'id_cliente'] = 301

## Verificando
display(
    df_clientes.loc[[46, 300]]
)

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
46,47,Wesley Araujo,Recife,ES,65+,PF
300,301,Carlos Neto,Niterói,RJ,36-45,Corporativo

# Auditoria do DataFrame Funcionários

Esta etapa busca validar informações cadastrais e funcionais dos colaboradores, incluindo salários, datas de admissão, cargos e departamentos.

## Diagnóstico de Qualidade dos Dados

| Coluna | Problema Identificado | Quantidade de Ocorrências | Severidade |
|---------|----------------------|--------------------------|------------|
| salario | Valores monetários armazenados como texto, exigindo limpeza e conversão para formato numérico | XX | 🟡 Média |
| salario | Presença de valores incompatíveis com o padrão observado na distribuição salarial | XX | 🔴 Alta |
| data_admissao | Tipagem inadequada para análise temporal | XX | 🟡 Média |
| cargo | Falta de padronização textual | XX | 🟢 Baixa |
| departamento | Presença de abreviações e variações de nomenclatura | XX | 🟡 Média |

In [18]:
## Avaliando estrutura e qualidade dos registros cadastrais

df_funcionarios.info()
df_funcionarios

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    str
 6   data_admissao   134 non-null    str
dtypes: int64(2), str(5)
memory usage: 7.5 KB

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,"""2.221,00""",2020-08-16
130,131,12,Abel Correia,Gerente,Administração,"""8.404,00""",2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,"""2.700,00""",2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,"""1.976,00""",2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,"""2.442,00""",2023-02-17

In [19]:
## Tratando inconsistências identificadas no cadastro de funcionários

## Convertendo salários para formato numérico
df_funcionarios['salario'] = (
    df_funcionarios['salario']
    .astype(str)
    .str.replace('"', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)
df_funcionarios['salario'] = pd.to_numeric(
    df_funcionarios['salario'],
    errors='coerce'
)

display(df_funcionarios)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,2139.0,2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,1746.0,2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,5356.0,2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,2070.0,2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,1572.0,2018-10-16
...,...,...,...,...,...,...,...
129,130,12,Fernanda Cruz,Manutenção,Manutenção,2221.0,2020-08-16
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28
131,132,12,Yuri Castro,Recepcionista,Recepção,2700.0,2021-01-22
132,133,12,Yuri Castro,segurança,Segurança,1976.0,2021-10-08
133,134,12,Eduardo Lopes,Recepcionista,Recepção,2442.0,2023-02-17

In [20]:
## Convertendo datas de admissão para formato datetime
df_funcionarios['data_admissao'] = pd.to_datetime(
    df_funcionarios['data_admissao'],
    format='mixed',
    dayfirst=True,
    errors='coerce')

print('Tipo:', df_funcionarios['data_admissao'].dtype)
print('NaT (não convertidos):', df_funcionarios['data_admissao'].isnull().sum())

Tipo: datetime64[us]
NaT (não convertidos): 0

In [21]:
## Investigando possíveis valores atípicos na distribuição salarial

print(df_funcionarios[df_funcionarios['salario'] < 0])

Q1 = df_funcionarios['salario'].quantile(0.25)
Q3 = df_funcionarios['salario'].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_funcionarios[
    (df_funcionarios['salario'] < limite_inferior) |
    (df_funcionarios['salario'] > limite_superior)
]

display(outliers)

    id_funcionario  id_unidade           nome      cargo departamento  \
10              11           1  Gabriela Lima  camareira         Gov.

    salario data_admissao
10  -2800.0    2020-11-12

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
2,3,1,Sara Teixeira,analista financeiro,Financeiro,5356.0,2022-01-03
10,11,1,Gabriela Lima,camareira,Gov.,-2800.0,2020-11-12
21,22,2,Ximena Godoi,ANALISTA FINANCEIRO,Financeiro,5534.0,2019-02-06
24,25,3,Ursula Pinto,ANALISTA FINANCEIRO,Financeiro,5569.0,2020-11-18
25,26,3,Gabriela Lima,MANUTENÇÃO,Manutenção,999999.0,2019-05-03
26,27,3,Gabriela Lima,ANALISTA FINANCEIRO,Financeiro,5226.0,2021-04-13
27,28,3,Ana Silva,Analista Financeiro,Financeiro,5498.0,2018-08-24
39,40,4,Elena Santos,Analista Financeiro,Financeiro,5659.0,2019-03-28
40,41,4,Ivan Azevedo,Analista Financeiro,Financeiro,5237.0,2018-11-24
49,50,5,Julia Monteiro,Gerente,Administração,8363.0,2020-05-17
50,51,5,Lucas Souza,Gerente,Administração,8855.0,2022-09-15
53,54,6,Natalia Campos,Analista Financeiro,Financeiro,5601.0,2022-12-26
56,57,6,Beatriz Dias,Analista Financeiro,Financeiro,5390.0,2022-12-23
57,58,6,Fernanda Cruz,gerente,Administração,8495.0,2024-04-26
66,67,7,Nicolas Cunha,Gerente,Administração,8411.0,2018-03-24
67,68,7,Ursula Pinto,Gerente,Administração,8920.0,2019-02-24
69,70,7,Paulo Ribeiro,Gerente,Administração,8349.0,2020-07-07
84,85,9,Natalia Campos,Analista Financeiro,Financeiro,5903.0,2023-08-05
97,98,10,Henrique Rocha,Analista Financeiro,Financeiro,5664.0,2022-12-13
118,119,11,Carlos Neto,Gerente,Admin.,8677.0,2022-04-08
130,131,12,Abel Correia,Gerente,Administração,8404.0,2018-10-28

### Análise de Valores Atípicos

Foi realizada uma análise estatística da coluna de salários utilizando o método do Intervalo Interquartil (IQR).

Os registros identificados como potenciais outliers foram avaliados individualmente para verificar se representavam salários válidos ou inconsistências de cadastro.

In [22]:
## Corrigindo registros salariais inconsistentes com os valores informados pela Empresa

correcoes = {
    11: 1950.00,
    26: 2300.00
}

for id_funcionario, salario in correcoes.items():
    df_funcionarios.loc[
        df_funcionarios['id_funcionario'] == id_funcionario,
        'salario'
    ] = salario

display(
    df_funcionarios.loc[
        df_funcionarios['id_funcionario'].isin([11, 26]),
        ['id_funcionario', 'nome', 'salario']
    ]
)

    id_funcionario           nome  salario
10              11  Gabriela Lima   1950.0
25              26  Gabriela Lima   2300.0

In [23]:
## Identificando variações de nomenclatura em cargos e departamentos

display(df_funcionarios['cargo'].value_counts())
display(df_funcionarios['departamento'].value_counts())

cargo
Auxiliar de Limpeza    16
Segurança              16
Manutenção             15
Camareira              14
Cozinheiro             10
Recepcionista           9
Analista Financeiro     9
Gerente                 8
MANUTENÇÃO              6
ANALISTA FINANCEIRO     3
cozinheiro              3
segurança               3
CAMAREIRA               3
camareira               2
Manutenção              2
Camareira               2
RECEPCIONISTA           2
COZINHEIRO              2
recepcionista           2
Recepcionista           2
analista financeiro     1
gerente                 1
AUXILIAR DE LIMPEZA     1
SEGURANÇA               1
manutenção              1
Name: count, dtype: int64

departamento
Governança             30
Manutenção             24
Segurança              20
Recepção               15
Financeiro             13
Alimentos e Bebidas    13
Gov.                    8
Administração           8
A&B                     2
Admin.                  1
Name: count, dtype: int64

In [24]:
## Padronizando cargos e departamentos para garantir consistência analítica
df_funcionarios['cargo'] = (
    df_funcionarios['cargo']
    .str.strip()
    .str.title()
)

df_funcionarios['departamento'] = (
    df_funcionarios['departamento']
    .str.strip()
    .str.title()
)

mapa = {
    'A&B': 'Alimentos e Bebidas',
    'Alimentos E Bebidas' : 'Alimentos e Bebidas',
    'Admin.': 'Administração',
    'Gov.': 'Governança'
}
df_funcionarios['departamento'] = df_funcionarios['departamento'].replace(mapa)

display(df_funcionarios['cargo'].value_counts())
display(df_funcionarios['departamento'].value_counts())

cargo
Manutenção             24
Camareira              21
Segurança              20
Auxiliar De Limpeza    17
Recepcionista          15
Cozinheiro             15
Analista Financeiro    13
Gerente                 9
Name: count, dtype: int64

departamento
Governança             38
Manutenção             24
Segurança              20
Recepção               15
Alimentos e Bebidas    15
Financeiro             13
Administração           9
Name: count, dtype: int64

# Auditoria do DataFrame Reservas

Por se tratar do principal conjunto operacional da empresa, esta auditoria avaliará informações relacionadas às reservas, períodos de hospedagem, avaliações dos hóspedes e métodos de pagamento.

## Diagnóstico de Qualidade dos Dados

| Coluna | Problema Identificado | Quantidade de Ocorrências | Severidade |
|---------|----------------------|--------------------------|------------|
| id_canal | Presença de registros incompatíveis com o tipo de dado esperado | XX | 🟡 Média |
| data_checkin | Tipagem inadequada para operações temporais | XX | 🟡 Média |
| data_checkout | Tipagem inadequada para operações temporais | XX | 🟡 Média |
| qtd_diarias | Quantidade de diárias incompatível com o período registrado | XX | 🔴 Alta |
| avaliacao_hospede | Registros incompatíveis com a escala de avaliação adotada | XX | 🟡 Média |
| num_hospedes | Quantidade de hóspedes inconsistente em algumas reservas | XX | 🟡 Média |
| status_reserva | Falta de padronização textual | XX | 🟢 Baixa |
| forma_pagamento | Presença de abreviações e nomenclaturas divergentes | XX | 🟢 Baixa |

In [25]:
## Avaliando estrutura e qualidade dos registros de reservas

df_reservas.info()
df_reservas

<class 'pandas.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         2457 non-null   int64
 1   id_unidade         2457 non-null   int64
 2   id_tipo_quarto     2457 non-null   int64
 3   id_cliente         2457 non-null   int64
 4   id_canal           2345 non-null   str
 5   data_checkin       2457 non-null   str
 6   data_checkout      2457 non-null   str
 7   qtd_diarias        2457 non-null   int64
 8   num_hospedes       2457 non-null   int64
 9   avaliacao_hospede  2120 non-null   str
 10  status_reserva     2457 non-null   str
 11  forma_pagamento    2457 non-null   str
dtypes: int64(6), str(6)
memory usage: 230.5 KB

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
0,1,5,1,3,2.0,2024-04-28,2024-04-30,2,1,4.0,confirmada,Cartão de Crédito
1,2,5,1,261,4.0,2023-09-28,2023-10-01,3,2,1.0,concluída,PIX
2,3,10,4,49,4.0,2023-08-01,2023-08-06,5,1,9.0,concluída,Cartão de Crédito
3,4,6,2,23,2.0,2023-02-18,2023-02-21,3,1,9.0,cancelada,PIX
4,5,7,1,42,1.0,2023-01-12,2023-01-19,7,1,6.0,confirmada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2452,2453,10,3,210,4.0,2023-10-22,2023-10-27,5,1,9.0,confirmada,Cartão de Débito
2453,2454,7,3,271,2.0,2024-08-08,2024-08-14,6,2,6.0,confirmada,PIX
2454,2455,7,1,143,1.0,2023-07-26,2023-07-27,1,2,6.0,confirmada,Transferência
2455,2456,8,4,176,1.0,2023-05-10,2023-05-17,7,1,6.0,concluída,Cartão de Débito
2456,2457,6,3,160,1.0,2023-07-01,2023-07-05,4,1,9.0,confirmada,Cartão de Crédito

In [26]:
## Avaliando indicadores que possam revelar inconsistências operacionais

display(df_reservas[['qtd_diarias', 'num_hospedes']].describe())
display(df_reservas['avaliacao_hospede'].unique()[:20])

       qtd_diarias  num_hospedes
count  2457.000000   2457.000000
mean      3.547416      1.820106
std       1.971780      0.862843
min      -1.000000     -2.000000
25%       2.000000      1.000000
50%       3.000000      2.000000
75%       5.000000      2.000000
max       7.000000      4.000000

<StringArray>
[ '4.0',  '1.0',  '9.0',  '6.0', '10.0',    nan,  '2.0',  '8.0',  '7.0',
 '11.0',  '3.0',  '0.0', '-3.0']
Length: 13, dtype: str

In [27]:
## Convertendo datas de check-in e check-out para datetime
df_reservas['data_checkin'] = pd.to_datetime(
    df_reservas['data_checkin'],
    errors='coerce'
)

df_reservas['data_checkout'] = pd.to_datetime(
    df_reservas['data_checkout'],
    errors='coerce'
)

## Convertendo id_canal para int
df_reservas['id_canal'] = (
    pd.to_numeric(
        df_reservas['id_canal'],
        errors='coerce'
    )
    .astype('Int64')
)
print('Tipo:', df_reservas['data_checkin'].dtype)
print('Tipo:', df_reservas['data_checkout'].dtype)

Tipo: datetime64[us]
Tipo: datetime64[us]

### Validação da Duração das Reservas

Foi realizada a comparação entre as datas de check-in e check-out e a quantidade de diárias registrada em cada reserva.

Os registros com divergências foram corrigidos para refletir corretamente o período efetivo de hospedagem.

In [28]:
## Corrigindo reservas com quantidade de diárias inconsistente

correcoes = {
    728: 4, 955: 4, 1134: 2,
    1152: 5, 1448: 2, 1581: 2,
    2312: 2, 2384: 2}

for id_reserva, qtd_diarias in correcoes.items():
    df_reservas.loc[
        df_reservas['id_reserva'] == id_reserva,
        'qtd_diarias'
    ] = qtd_diarias

display(df_reservas.loc[df_reservas['id_reserva'].isin([728, 955, 1134, 1152, 1448, 1581, 2312, 2384]),
        ['id_reserva', 'qtd_diarias']
    ]
)

      id_reserva  qtd_diarias
727          728            4
954          955            4
1133        1134            2
1151        1152            5
1447        1448            2
1580        1581            2
2311        2312            2
2383        2384            2

In [29]:
## Convertendo avaliações para formato numérico

df_reservas['avaliacao_hospede'] = (
    pd.to_numeric(
        df_reservas['avaliacao_hospede'],
        errors='coerce'
    )
    .astype('Int64')
)

print(df_reservas['avaliacao_hospede'].dtype)

## Corrigindo avaliações incompatíveis com a escala adotada
correcoes = {
    37: 8, 194: 2, 902: 10,
    933: 7, 1538: 3, 1718: 4,
    1866: 3, 2073: 9, 2167: 5, 2210: 2}

for id_reserva, avaliacao_hospede in correcoes.items():
    df_reservas.loc[
        df_reservas['id_reserva'] == id_reserva,
        'avaliacao_hospede'
    ] = avaliacao_hospede

display(df_reservas.loc[df_reservas['id_reserva'].isin([37, 194, 902, 933, 1538, 1718, 1866, 2073, 2167, 2210]),
        ['id_reserva', 'avaliacao_hospede']
    ]
)

Int64

      id_reserva  avaliacao_hospede
36            37                  8
193          194                  2
901          902                 10
932          933                  7
1537        1538                  3
1717        1718                  4
1865        1866                  3
2072        2073                  9
2166        2167                  5
2209        2210                  2

In [30]:
## Corrigindo registros com quantidade de hóspedes inconsistente

correcoes = {
    568: 2, 675: 3, 903: 2,
    1201: 3, 1883: 1, 2427: 1,}

for id_reserva, num_hospedes in correcoes.items():
    df_reservas.loc[
        df_reservas['id_reserva'] == id_reserva,
        'num_hospedes'
    ] = num_hospedes

display(df_reservas.loc[df_reservas['id_reserva'].isin([568, 675, 903, 1201, 1883, 2427]),
        ['id_reserva', 'num_hospedes']
    ]
)

      id_reserva  num_hospedes
567          568             2
674          675             3
902          903             2
1200        1201             3
1882        1883             1
2426        2427             1

In [31]:
## Avaliando padrões de preenchimento em status e formas de pagamento

display(df_reservas['status_reserva'].value_counts())
display(df_reservas['forma_pagamento'].value_counts())

status_reserva
confirmada     1711
cancelada       359
concluída       214
no-show         125
CONFIRMADA       17
Confirmada       13
conf.             7
Concluída         3
Concluida         3
CANCELADA         2
Cancelada         1
cancel.           1
NO-SHOW           1
Name: count, dtype: int64

forma_pagamento
Dinheiro             501
Cartão de Débito     499
PIX                  484
Transferência        467
Cartão de Crédito    453
CC                     9
Pix                    7
cred                   5
pix                    5
dinheiro               4
C. Crédito             4
cash                   4
cartao credito         3
CD                     3
transferencia          2
DINHEIRO               2
ted                    2
déb                    1
cartao debito          1
TED                    1
Name: count, dtype: int64

In [32]:

## Padronizando status das reservas e formas de pagamento
df_reservas['status_reserva'] = (
    df_reservas['status_reserva']
    .str.strip()
    .str.title()
)

df_reservas['forma_pagamento'] = (
    df_reservas['forma_pagamento']
    .str.strip()
    .str.title()
)

mapa = {
    'Cancel.': 'Cancelada',
    'Concluida' : 'Concluída',
    'Conf.': 'Confirmada',
    'Cash': 'Dinheiro',
    'C. Crédito': 'Cartão De Crédito', 'Cartao Credito': 'Cartão De Crédito',
    'Cc': 'Cartão De Crédito', 'Cred': 'Cartão De Crédito',
    'Cartao Debito': 'Cartão De Débito', 'Cd': 'Cartão De Débito', 'Déb': 'Cartão De Débito',
    'Ted': 'Transferência', 'Transferencia': 'Transferência'}
df_reservas['status_reserva'] = df_reservas['status_reserva'].replace(mapa)
df_reservas['forma_pagamento'] = df_reservas['forma_pagamento'].replace(mapa)

# Conclusão da Auditoria

Durante a auditoria foram identificadas inconsistências relacionadas à tipagem de dados, padronização textual, duplicidades, valores ausentes e registros incompatíveis com as regras de negócio.

Após os tratamentos aplicados, os datasets encontram-se validados e preparados para utilização em análises e visualizações posteriores.

In [33]:
## Baixar CSV
## O parâmetro lineterminator='\n' é adicionado para garantir que cada linha seja terminada 
## com o mesmo padrao dos arquivos de entrada
# O separador de campos (sep=) é definido como ';' para manter a consistência com os arquivos originais, 
# e index=False é usado para evitar que o índice do DataFrame seja incluído no arquivo CSV de saída.

df_canais_venda.to_csv('canais de venda auditado.csv',  sep=';', index=False, lineterminator='\n')
df_reservas.to_csv('Reservas auditado.csv',             sep=';', index=False, lineterminator='\n')
df_unidades.to_csv('Unidades auditado.csv',             sep=';', index=False, lineterminator='\n')
df_tipos_quarto.to_csv('Tipos de Quarto auditado.csv',  sep=';', index=False, lineterminator='\n')
df_funcionarios.to_csv('Funcionarios auditado.csv',     sep=';', index=False, lineterminator='\n')
df_clientes.to_csv('Clientes auditado.csv',             sep=';', index=False, lineterminator='\n')